// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yxxbntptkzcewvfxevdi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl4eGJudHB0a3pjZXd2ZnhldmRpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1Mjc3MzEsImV4cCI6MjA2MTEwMzczMX0.ncEvmcUuChK9aAvBAw_Ih3trUfLOgKyZ3y6J8Kei3sM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);